from rest_framework import serializers
from .models import ChannelConfig


class ChannelConfigSerializer(serializers.ModelSerializer):
    class Meta:
        model = ChannelConfig
        exclude = ['credentials']  # Never expose credentials
        read_only_fields = ['id', 'organization', 'created_at', 'updated_at']


class WebChatInboundSerializer(serializers.Serializer):
    organization_slug = serializers.CharField(required=False, allow_blank=True)
    session_id = serializers.CharField(max_length=120)
    session_token = serializers.CharField(required=False, allow_blank=True, max_length=255)
    message = serializers.CharField(max_length=4000)
    nombre = serializers.CharField(required=False, allow_blank=True, max_length=100)
    apellido = serializers.CharField(required=False, allow_blank=True, max_length=100)
    email = serializers.EmailField(required=False, allow_blank=True)
    telefono = serializers.CharField(required=False, allow_blank=True, max_length=30)


class PublicAppChatSessionSerializer(serializers.Serializer):
    session_id = serializers.CharField(max_length=120)


class WhatsAppConnectionSerializer(serializers.Serializer):
    id = serializers.CharField()
    channel = serializers.CharField()
    is_active = serializers.BooleanField()
    webhook_url = serializers.CharField(allow_blank=True)
    token_configured = serializers.BooleanField()
    phone_number_id = serializers.CharField(allow_blank=True)
    whatsapp_business_account_id = serializers.CharField(allow_blank=True)
    business_portfolio_id = serializers.CharField(allow_blank=True)
    display_phone_number = serializers.CharField(allow_blank=True)
    verified_name = serializers.CharField(allow_blank=True)
    onboarding_status = serializers.CharField(allow_blank=True)
    webhook_status = serializers.CharField(allow_blank=True)
    template_sync_status = serializers.CharField(allow_blank=True)
    quality_status = serializers.CharField(allow_blank=True)
    messaging_limit_status = serializers.CharField(allow_blank=True)
    capabilities = serializers.ListField(child=serializers.CharField(), default=list)
    last_sync_at = serializers.DateTimeField(allow_null=True)
    last_webhook_received_at = serializers.DateTimeField(allow_null=True)
    default_send_behavior = serializers.CharField(allow_blank=True)
    fallback_handling = serializers.CharField(allow_blank=True)
    auto_sync_templates = serializers.BooleanField()
    alert_on_webhook_failure = serializers.BooleanField()
    internal_label = serializers.CharField(allow_blank=True)
    internal_notes = serializers.CharField(allow_blank=True)
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()


class WhatsAppConnectionUpdateSerializer(serializers.Serializer):
    is_active = serializers.BooleanField(required=False)
    webhook_url = serializers.URLField(required=False, allow_blank=True)
    access_token = serializers.CharField(required=False, allow_blank=True, write_only=True)
    phone_number_id = serializers.CharField(required=False, allow_blank=True)
    whatsapp_business_account_id = serializers.CharField(required=False, allow_blank=True)
    business_portfolio_id = serializers.CharField(required=False, allow_blank=True)
    display_phone_number = serializers.CharField(required=False, allow_blank=True)
    verified_name = serializers.CharField(required=False, allow_blank=True)
    onboarding_status = serializers.CharField(required=False, allow_blank=True)
    webhook_status = serializers.CharField(required=False, allow_blank=True)
    template_sync_status = serializers.CharField(required=False, allow_blank=True)
    quality_status = serializers.CharField(required=False, allow_blank=True)
    messaging_limit_status = serializers.CharField(required=False, allow_blank=True)
    capabilities = serializers.ListField(child=serializers.CharField(), required=False)
    default_send_behavior = serializers.CharField(required=False, allow_blank=True)
    fallback_handling = serializers.CharField(required=False, allow_blank=True)
    auto_sync_templates = serializers.BooleanField(required=False)
    alert_on_webhook_failure = serializers.BooleanField(required=False)
    internal_label = serializers.CharField(required=False, allow_blank=True)
    internal_notes = serializers.CharField(required=False, allow_blank=True)


class WhatsAppSimulateInboundSerializer(serializers.Serializer):
    phone = serializers.CharField(max_length=30)
    message = serializers.CharField(max_length=4000)
    message_type = serializers.CharField(required=False, allow_blank=True, default='text')


class WhatsAppEmbeddedSignupConfigSerializer(serializers.Serializer):
    enabled = serializers.BooleanField()
    app_id = serializers.CharField(allow_blank=True)
    config_id = serializers.CharField(allow_blank=True)
    feature = serializers.CharField()
    session_state = serializers.CharField(allow_blank=True)
    session_started_at = serializers.CharField(allow_blank=True, allow_null=True)
    session_status = serializers.CharField()
    webhook_url = serializers.CharField(allow_blank=True)
    verify_token = serializers.CharField(allow_blank=True)


class WhatsAppEmbeddedSignupStartSerializer(serializers.Serializer):
    session_state = serializers.CharField()
    session_started_at = serializers.CharField()
    session_status = serializers.CharField()


class WhatsAppEmbeddedSignupCompleteSerializer(serializers.Serializer):
    state = serializers.CharField()
    code = serializers.CharField(required=False, allow_blank=True)
    access_token = serializers.CharField(required=False, allow_blank=True, write_only=True)
    business_portfolio_id = serializers.CharField(required=False, allow_blank=True)
    whatsapp_business_account_id = serializers.CharField(required=False, allow_blank=True)
    phone_number_id = serializers.CharField(required=False, allow_blank=True)
    display_phone_number = serializers.CharField(required=False, allow_blank=True)
    verified_name = serializers.CharField(required=False, allow_blank=True)


class WebWidgetConnectionSerializer(serializers.Serializer):
    id = serializers.CharField()
    channel = serializers.CharField()
    organization_slug = serializers.CharField(allow_blank=True)
    is_active = serializers.BooleanField()
    widget_name = serializers.CharField(allow_blank=True)
    greeting_message = serializers.CharField(allow_blank=True)
    brand_color = serializers.CharField(allow_blank=True)
    position = serializers.CharField(allow_blank=True)
    allowed_domains = serializers.ListField(child=serializers.CharField(), default=list)
    launcher_label = serializers.CharField(allow_blank=True)
    require_consent = serializers.BooleanField()
    handoff_enabled = serializers.BooleanField()
    widget_script_url = serializers.CharField(allow_blank=True)
    embed_snippet = serializers.CharField(allow_blank=True)
    public_demo_url = serializers.CharField(allow_blank=True)
    install_status = serializers.CharField(allow_blank=True)
    verified_domains = serializers.ListField(child=serializers.CharField(), default=list)
    last_install_check_at = serializers.DateTimeField(allow_null=True)
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()


class WebWidgetPublicSerializer(serializers.Serializer):
    organization_slug = serializers.CharField(allow_blank=True)
    is_active = serializers.BooleanField()
    widget_name = serializers.CharField(allow_blank=True)
    greeting_message = serializers.CharField(allow_blank=True)
    brand_color = serializers.CharField(allow_blank=True)
    position = serializers.CharField(allow_blank=True)
    launcher_label = serializers.CharField(allow_blank=True)
    require_consent = serializers.BooleanField()
    handoff_enabled = serializers.BooleanField()
    public_demo_url = serializers.CharField(allow_blank=True)


class WebWidgetConnectionUpdateSerializer(serializers.Serializer):
    is_active = serializers.BooleanField(required=False)
    widget_name = serializers.CharField(required=False, allow_blank=True)
    brand_color = serializers.CharField(required=False, allow_blank=True)
    position = serializers.CharField(required=False, allow_blank=True)
    allowed_domains = serializers.ListField(child=serializers.CharField(), required=False)
    launcher_label = serializers.CharField(required=False, allow_blank=True)
    require_consent = serializers.BooleanField(required=False)
    handoff_enabled = serializers.BooleanField(required=False)


class AppChatConnectionSerializer(serializers.Serializer):
    id = serializers.CharField()
    channel = serializers.CharField()
    organization_slug = serializers.CharField(allow_blank=True)
    is_active = serializers.BooleanField()
    app_name = serializers.CharField(allow_blank=True)
    welcome_message = serializers.CharField(allow_blank=True)
    primary_color = serializers.CharField(allow_blank=True)
    accent_color = serializers.CharField(allow_blank=True)
    page_background_color = serializers.CharField(allow_blank=True)
    background_mode = serializers.CharField(allow_blank=True)
    background_treatment = serializers.CharField(allow_blank=True)
    hero_height = serializers.CharField(allow_blank=True)
    logo_size = serializers.CharField(allow_blank=True)
    banner_intensity = serializers.CharField(allow_blank=True)
    chat_density = serializers.CharField(allow_blank=True)
    hero_curve = serializers.CharField(allow_blank=True)
    carousel_style = serializers.CharField(allow_blank=True)
    social_visibility = serializers.CharField(allow_blank=True)
    component_style = serializers.CharField(allow_blank=True)
    layout_template = serializers.CharField(allow_blank=True)
    background_image_url = serializers.CharField(allow_blank=True)
    background_overlay = serializers.CharField(allow_blank=True)
    font_family = serializers.CharField(allow_blank=True)
    font_scale = serializers.CharField(allow_blank=True)
    presentation_style = serializers.CharField(allow_blank=True)
    surface_style = serializers.CharField(allow_blank=True)
    bubble_style = serializers.CharField(allow_blank=True)
    user_bubble_color = serializers.CharField(allow_blank=True)
    agent_bubble_color = serializers.CharField(allow_blank=True)
    header_logo_url = serializers.CharField(allow_blank=True)
    launcher_label = serializers.CharField(allow_blank=True)
    ticker_enabled = serializers.BooleanField()
    ticker_text = serializers.CharField(allow_blank=True)
    show_featured_products = serializers.BooleanField()
    instagram_url = serializers.CharField(allow_blank=True)
    tiktok_url = serializers.CharField(allow_blank=True)
    whatsapp_url = serializers.CharField(allow_blank=True)
    website_url = serializers.CharField(allow_blank=True)
    location_url = serializers.CharField(allow_blank=True)
    ios_bundle_ids = serializers.ListField(child=serializers.CharField(), default=list)
    android_package_names = serializers.ListField(child=serializers.CharField(), default=list)
    allowed_origins = serializers.ListField(child=serializers.CharField(), default=list)
    auth_mode = serializers.CharField(allow_blank=True)
    require_authentication = serializers.BooleanField()
    push_enabled = serializers.BooleanField()
    handoff_enabled = serializers.BooleanField()
    publishable_key = serializers.CharField(allow_blank=True)
    rest_endpoint = serializers.CharField(allow_blank=True)
    public_app_url = serializers.CharField(allow_blank=True)
    android_sdk_snippet = serializers.CharField(allow_blank=True)
    ios_sdk_snippet = serializers.CharField(allow_blank=True)
    install_status = serializers.CharField(allow_blank=True)
    verified_apps = serializers.ListField(child=serializers.CharField(), default=list)
    last_install_check_at = serializers.DateTimeField(allow_null=True)
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()


class AppChatPublicSerializer(serializers.Serializer):
    organization_slug = serializers.CharField(allow_blank=True)
    app_name = serializers.CharField(allow_blank=True)
    welcome_message = serializers.CharField(allow_blank=True)
    primary_color = serializers.CharField(allow_blank=True)
    accent_color = serializers.CharField(allow_blank=True)
    page_background_color = serializers.CharField(allow_blank=True)
    background_mode = serializers.CharField(allow_blank=True)
    background_treatment = serializers.CharField(allow_blank=True)
    hero_height = serializers.CharField(allow_blank=True)
    logo_size = serializers.CharField(allow_blank=True)
    banner_intensity = serializers.CharField(allow_blank=True)
    chat_density = serializers.CharField(allow_blank=True)
    hero_curve = serializers.CharField(allow_blank=True)
    carousel_style = serializers.CharField(allow_blank=True)
    social_visibility = serializers.CharField(allow_blank=True)
    component_style = serializers.CharField(allow_blank=True)
    layout_template = serializers.CharField(allow_blank=True)
    background_image_url = serializers.CharField(allow_blank=True)
    background_overlay = serializers.CharField(allow_blank=True)
    font_family = serializers.CharField(allow_blank=True)
    font_scale = serializers.CharField(allow_blank=True)
    presentation_style = serializers.CharField(allow_blank=True)
    surface_style = serializers.CharField(allow_blank=True)
    bubble_style = serializers.CharField(allow_blank=True)
    user_bubble_color = serializers.CharField(allow_blank=True)
    agent_bubble_color = serializers.CharField(allow_blank=True)
    header_logo_url = serializers.CharField(allow_blank=True)
    launcher_label = serializers.CharField(allow_blank=True)
    ticker_enabled = serializers.BooleanField()
    ticker_text = serializers.CharField(allow_blank=True)
    show_featured_products = serializers.BooleanField()
    instagram_url = serializers.CharField(allow_blank=True)
    tiktok_url = serializers.CharField(allow_blank=True)
    whatsapp_url = serializers.CharField(allow_blank=True)
    website_url = serializers.CharField(allow_blank=True)
    location_url = serializers.CharField(allow_blank=True)
    handoff_enabled = serializers.BooleanField()
    public_app_url = serializers.CharField(allow_blank=True)


class AppChatConnectionUpdateSerializer(serializers.Serializer):
    is_active = serializers.BooleanField(required=False)
    app_name = serializers.CharField(required=False, allow_blank=True)
    primary_color = serializers.CharField(required=False, allow_blank=True)
    accent_color = serializers.CharField(required=False, allow_blank=True)
    page_background_color = serializers.CharField(required=False, allow_blank=True)
    background_mode = serializers.CharField(required=False, allow_blank=True)
    background_treatment = serializers.CharField(required=False, allow_blank=True)
    hero_height = serializers.CharField(required=False, allow_blank=True)
    logo_size = serializers.CharField(required=False, allow_blank=True)
    banner_intensity = serializers.CharField(required=False, allow_blank=True)
    chat_density = serializers.CharField(required=False, allow_blank=True)
    hero_curve = serializers.CharField(required=False, allow_blank=True)
    carousel_style = serializers.CharField(required=False, allow_blank=True)
    social_visibility = serializers.CharField(required=False, allow_blank=True)
    component_style = serializers.CharField(required=False, allow_blank=True)
    layout_template = serializers.CharField(required=False, allow_blank=True)
    background_image_url = serializers.CharField(required=False, allow_blank=True)
    background_overlay = serializers.CharField(required=False, allow_blank=True)
    font_family = serializers.CharField(required=False, allow_blank=True)
    font_scale = serializers.CharField(required=False, allow_blank=True)
    presentation_style = serializers.CharField(required=False, allow_blank=True)
    surface_style = serializers.CharField(required=False, allow_blank=True)
    bubble_style = serializers.CharField(required=False, allow_blank=True)
    user_bubble_color = serializers.CharField(required=False, allow_blank=True)
    agent_bubble_color = serializers.CharField(required=False, allow_blank=True)
    header_logo_url = serializers.CharField(required=False, allow_blank=True)
    launcher_label = serializers.CharField(required=False, allow_blank=True)
    ticker_enabled = serializers.BooleanField(required=False)
    ticker_text = serializers.CharField(required=False, allow_blank=True)
    show_featured_products = serializers.BooleanField(required=False)
    instagram_url = serializers.CharField(required=False, allow_blank=True)
    tiktok_url = serializers.CharField(required=False, allow_blank=True)
    whatsapp_url = serializers.CharField(required=False, allow_blank=True)
    website_url = serializers.CharField(required=False, allow_blank=True)
    location_url = serializers.CharField(required=False, allow_blank=True)
    ios_bundle_ids = serializers.ListField(child=serializers.CharField(), required=False)
    android_package_names = serializers.ListField(child=serializers.CharField(), required=False)
    allowed_origins = serializers.ListField(child=serializers.CharField(), required=False)
    auth_mode = serializers.CharField(required=False, allow_blank=True)
    require_authentication = serializers.BooleanField(required=False)
    push_enabled = serializers.BooleanField(required=False)
    handoff_enabled = serializers.BooleanField(required=False)

    def validate(self, attrs):
        for key in ['background_image_url', 'header_logo_url']:
            value = attrs.get(key)
            if value is None or value == '':
                continue
            normalized = str(value).strip().lower()
            if normalized.startswith('data:') or normalized.startswith('javascript:'):
                raise serializers.ValidationError({key: 'Solo se permiten URLs seguras para medios.'})
        return attrs


class AppChatInboundSerializer(serializers.Serializer):
    organization_slug = serializers.CharField(required=False, allow_blank=True)
    session_id = serializers.CharField(max_length=120)
    session_token = serializers.CharField(required=False, allow_blank=True, max_length=255)
    message = serializers.CharField(max_length=4000)
    platform = serializers.ChoiceField(required=False, choices=['ios', 'android', 'unknown'], default='unknown')
    app_user_id = serializers.CharField(required=False, allow_blank=True, max_length=120)
    nombre = serializers.CharField(required=False, allow_blank=True, max_length=100)
    apellido = serializers.CharField(required=False, allow_blank=True, max_length=100)
    email = serializers.EmailField(required=False, allow_blank=True)
    telefono = serializers.CharField(required=False, allow_blank=True, max_length=30)


class AppChatConversationQuerySerializer(serializers.Serializer):
    session_id = serializers.CharField(max_length=120)
    session_token = serializers.CharField(max_length=255)


class DatabaseConnectionSerializer(serializers.Serializer):
    id = serializers.CharField()
    channel = serializers.CharField()
    is_active = serializers.BooleanField()
    engine = serializers.CharField(allow_blank=True)
    host = serializers.CharField(allow_blank=True)
    port = serializers.IntegerField()
    database_name = serializers.CharField(allow_blank=True)
    schema_name = serializers.CharField(allow_blank=True)
    username = serializers.CharField(allow_blank=True)
    password_configured = serializers.BooleanField()
    ssl_mode = serializers.CharField(allow_blank=True)
    connection_status = serializers.CharField(allow_blank=True)
    last_tested_at = serializers.DateTimeField(allow_null=True)
    last_error = serializers.CharField(allow_blank=True)
    default_lookup_table = serializers.CharField(allow_blank=True)
    document_column = serializers.CharField(allow_blank=True)
    full_name_column = serializers.CharField(allow_blank=True)
    phone_column = serializers.CharField(allow_blank=True)
    email_column = serializers.CharField(allow_blank=True)
    affiliate_type_column = serializers.CharField(allow_blank=True)
    last_lookup_at = serializers.DateTimeField(allow_null=True)
    capabilities = serializers.ListField(child=serializers.CharField(), default=list)
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()


class DatabaseConnectionUpdateSerializer(serializers.Serializer):
    is_active = serializers.BooleanField(required=False)
    engine = serializers.ChoiceField(required=False, choices=['postgresql', 'sqlite'])
    host = serializers.CharField(required=False, allow_blank=True)
    port = serializers.IntegerField(required=False, min_value=1, max_value=65535)
    database_name = serializers.CharField(required=False, allow_blank=True)
    schema_name = serializers.CharField(required=False, allow_blank=True)
    username = serializers.CharField(required=False, allow_blank=True)
    password = serializers.CharField(required=False, allow_blank=True, write_only=True)
    ssl_mode = serializers.CharField(required=False, allow_blank=True)
    default_lookup_table = serializers.CharField(required=False, allow_blank=True)
    document_column = serializers.CharField(required=False, allow_blank=True)
    full_name_column = serializers.CharField(required=False, allow_blank=True)
    phone_column = serializers.CharField(required=False, allow_blank=True)
    email_column = serializers.CharField(required=False, allow_blank=True)
    affiliate_type_column = serializers.CharField(required=False, allow_blank=True)
    capabilities = serializers.ListField(child=serializers.CharField(), required=False)


class DatabaseLookupSerializer(serializers.Serializer):
    document_number = serializers.CharField(max_length=50)
