# Generated by Django 5.0.6 on 2026-04-04 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPerformanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('conversations_handled', models.PositiveIntegerField(default=0)),
                ('conversations_resolved', models.PositiveIntegerField(default=0)),
                ('avg_response_time_s', models.FloatField(default=0.0)),
                ('avg_resolution_time_s', models.FloatField(default=0.0)),
                ('escalations_caused', models.PositiveIntegerField(default=0)),
                ('csat_score', models.FloatField(default=0.0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('online_minutes', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_performance', to='accounts.organization')),
            ],
            options={
                'db_table': 'agent_performance_snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'date'], name='agent_perfo_organiz_1a7c4a_idx')],
                'unique_together': {('agent', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CollabNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('note', 'Note'), ('escalation_reason', 'Escalation Reason'), ('resolution_note', 'Resolution Note'), ('handoff', 'Handoff'), ('warning', 'Warning')], default='note', max_length=30)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collab_notes', to='conversations.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_notes', to='accounts.organization')),
            ],
            options={
                'db_table': 'collab_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'conversation'], name='collab_note_organiz_3c9e70_idx')],
            },
        ),
    ]
