# Generated by Django 5.0.6 on 2026-04-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversation_fields'),
        ('conversations', '0003_conversation_commercial_outcome'),
    ]

    operations = [
    ]
