# Generated by Django 5.0.6 on 2026-04-04 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('trigger', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='accounts.organization')),
            ],
            options={
                'db_table': 'flows',
                'ordering': ['-updated_at'],
            },
        ),
    ]
