# Generated by Django 5.0.6 on 2026-04-04 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterDecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_id', models.CharField(max_length=100)),
                ('intent', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(max_length=20)),
                ('route_type', models.CharField(max_length=60)),
                ('agent', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('post_actions', models.JSONField(default=list)),
                ('full_decision', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='router_decisions', to='conversations.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='router_decisions', to='conversations.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='router_decisions', to='accounts.organization')),
            ],
            options={
                'db_table': 'router_decision_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='router_deci_organiz_7cd640_idx'), models.Index(fields=['conversation'], name='router_deci_convers_a23a48_idx'), models.Index(fields=['intent'], name='router_deci_intent_aaabe6_idx')],
            },
        ),
    ]
