# Generated by Django 5.0.6 on 2026-04-04 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Colombia', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('plan', models.CharField(choices=[('pilot', 'Pilot'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='pilot', max_length=20)),
                ('max_agents', models.PositiveIntegerField(default=3)),
                ('monthly_message_limit', models.PositiveIntegerField(default=1000)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('whatsapp_api_token', models.TextField(blank=True)),
                ('timezone', models.CharField(default='America/Bogota', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, db_index=True, max_length=30)),
                ('cedula', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('trabajador', 'Trabajador'), ('empleador', 'Empleador'), ('pensionado', 'Pensionado'), ('independiente', 'Independiente'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('tipo_afiliado', models.CharField(blank=True, max_length=30)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('web', 'Web Chat'), ('tiktok', 'TikTok'), ('email', 'Email'), ('telegram', 'Telegram')], default='whatsapp', help_text='Last known channel for this contact', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.organization')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['nombre', 'apellido'],
                'indexes': [models.Index(fields=['organization', 'tipo'], name='contacts_organiz_968ad1_idx'), models.Index(fields=['organization', 'telefono'], name='contacts_organiz_d6e784_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('asesor', 'Asesor')], default='asesor', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('max_concurrent_chats', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=64)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['nombre', 'apellido'],
                'indexes': [models.Index(fields=['organization', 'rol'], name='users_organiz_4b9360_idx'), models.Index(fields=['organization', 'is_available'], name='users_organiz_4b8d0d_idx')],
            },
        ),
    ]
