# Generated by Django 5.0.6 on 2026-04-04 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tipo', models.CharField(choices=[('pilot', 'Pilot'), ('base', 'Base'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='base', max_length=20)),
                ('price_cop', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_channels', models.IntegerField(default=1)),
                ('max_agents', models.IntegerField(default=1)),
                ('max_conversations_month', models.IntegerField(default=500)),
                ('extra_conversation_price_cop', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('highlight', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['price_cop'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('conversations_used', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-started_at'],
            },
        ),
    ]
