# Generated by Django 5.0.6 on 2026-04-04 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('web', 'Web Chat'), ('onboarding', 'Onboarding Profile'), ('database', 'Database'), ('tiktok', 'TikTok'), ('email', 'Email'), ('telegram', 'Telegram')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('webhook_url', models.URLField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_configs', to='accounts.organization')),
            ],
            options={
                'db_table': 'channel_configs',
                'unique_together': {('organization', 'channel')},
            },
        ),
    ]
