# Generated by Django 5.0.6 on 2026-04-04 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('sales', 'Sales Agent'), ('marketing', 'Marketing Agent'), ('operations', 'Operations Agent'), ('support', 'Support Agent')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude'), ('heuristic', 'Heuristic')], default='openai', max_length=20)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('system_prompt', models.TextField(blank=True)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to='accounts.organization')),
            ],
            options={
                'db_table': 'ai_agents',
                'ordering': ['agent_type'],
                'unique_together': {('organization', 'agent_type')},
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('performance', 'Performance'), ('channel', 'Channel'), ('intent', 'Intent Pattern'), ('agent', 'Agent'), ('customer', 'Customer'), ('operations', 'Operations')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('positive', 'Positive')], default='info', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('metric_delta', models.FloatField(blank=True, null=True)),
                ('action_suggested', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='accounts.organization')),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['organization', 'category'], name='ai_insights_organiz_6abc60_idx'), models.Index(fields=['organization', 'is_read'], name='ai_insights_organiz_c46357_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIMemoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference'), ('resolution', 'Resolved Case'), ('escalation', 'Escalation Pattern'), ('faq', 'FAQ')], default='fact', max_length=20)),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('confidence', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memories', to='accounts.organization')),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.conversation')),
            ],
            options={
                'db_table': 'ai_memory_entries',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['organization', 'memory_type'], name='ai_memory_e_organiz_3b8be2_idx'), models.Index(fields=['organization', 'is_active'], name='ai_memory_e_organiz_3306d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIPerformanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('model_name', models.CharField(default='gpt-4o', max_length=100)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('successful_calls', models.PositiveIntegerField(default=0)),
                ('failed_calls', models.PositiveIntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('total_tokens_in', models.PositiveIntegerField(default=0)),
                ('total_tokens_out', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('bot_resolution_rate', models.FloatField(default=0.0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_performance_logs', to='accounts.organization')),
            ],
            options={
                'db_table': 'ai_performance_logs',
                'ordering': ['-date'],
                'unique_together': {('organization', 'date', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=200)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='accounts.organization')),
            ],
            options={
                'db_table': 'ai_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='ai_tasks_organiz_7e6db2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesAgentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('decision', models.CharField(max_length=30)),
                ('handoff_needed', models.BooleanField(default=False)),
                ('handoff_reason', models.CharField(blank=True, max_length=200)),
                ('products_shown', models.JSONField(default=list)),
                ('recommended_actions', models.JSONField(default=list)),
                ('context_used', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_agent_logs', to='conversations.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_agent_logs', to='accounts.organization')),
            ],
            options={
                'db_table': 'sales_agent_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'stage'], name='sales_agent_organiz_118338_idx'), models.Index(fields=['conversation'], name='sales_agent_convers_d1b4e1_idx')],
            },
        ),
    ]
