# Generated by Django 5.0.6 on 2026-04-04 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0001_initial'),
        ('ecommerce', '0001_initial'),
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('faq', 'FAQ'), ('winning_reply', 'Winning reply'), ('objection', 'Objection')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('source_question', models.TextField(blank=True)),
                ('proposed_answer', models.TextField(blank=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence_count', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_candidates', to='knowledge_base.kbarticle')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_candidates', to='conversations.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_candidates', to='accounts.organization')),
            ],
            options={
                'db_table': 'analytics_learning_candidates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('canal', models.CharField(max_length=20)),
                ('total_conversations', models.IntegerField(default=0)),
                ('resolved', models.IntegerField(default=0)),
                ('escalated', models.IntegerField(default=0)),
                ('avg_response_time_s', models.FloatField(default=0)),
                ('csat_score', models.FloatField(default=0)),
                ('ai_handled', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='accounts.organization')),
            ],
            options={
                'db_table': 'metrics_snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentExtractionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('service', 'Service'), ('pricing_rule', 'Pricing rule'), ('policy', 'Policy'), ('flow_hint', 'Flow hint')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('confidence', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_extraction_candidates', to='knowledge_base.kbarticle')),
                ('approved_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_extraction_candidates', to='ecommerce.product')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_extraction_candidates', to='accounts.organization')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_candidates', to='knowledge_base.kbdocument')),
            ],
            options={
                'db_table': 'analytics_document_extraction_candidates',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['organization', 'status', 'kind'], name='analytics_d_organiz_fa605a_idx'), models.Index(fields=['organization', 'updated_at'], name='analytics_d_organiz_10adbb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentextractioncandidate',
            constraint=models.UniqueConstraint(fields=('organization', 'kind', 'fingerprint'), name='uniq_doc_extraction_candidate_per_org'),
        ),
        migrations.AddIndex(
            model_name='learningcandidate',
            index=models.Index(fields=['organization', 'status', 'kind'], name='analytics_l_organiz_500374_idx'),
        ),
        migrations.AddIndex(
            model_name='learningcandidate',
            index=models.Index(fields=['organization', 'updated_at'], name='analytics_l_organiz_33ffaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningcandidate',
            constraint=models.UniqueConstraint(fields=('organization', 'kind', 'fingerprint'), name='uniq_learning_candidate_per_org'),
        ),
        migrations.AddIndex(
            model_name='metricssnapshot',
            index=models.Index(fields=['organization', 'date'], name='metrics_sna_organiz_dec9ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metricssnapshot',
            unique_together={('organization', 'date', 'canal')},
        ),
    ]
