# Generated by Django 5.0.6 on 2026-04-04 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(blank=True, choices=[('faq', 'FAQ General'), ('objection', 'Manejo de Objeción'), ('closing', 'Técnica de Cierre'), ('brand_voice', 'Voz de Marca'), ('policy', 'Política del Negocio'), ('product_context', 'Contexto de Producto')], default='faq', max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('embedding_vector', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_articles', to='accounts.organization')),
            ],
            options={
                'db_table': 'kb_articles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KBDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='kb_documents/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='knowledge_base.kbarticle')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_documents', to='accounts.organization')),
            ],
            options={
                'db_table': 'kb_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['organization', 'status'], name='kb_articles_organiz_1a5efc_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['organization', 'category'], name='kb_articles_organiz_0de095_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['organization', 'purpose'], name='kb_articles_organiz_90be3c_idx'),
        ),
        migrations.AddIndex(
            model_name='kbdocument',
            index=models.Index(fields=['organization', 'processing_status'], name='kb_document_organiz_8bde9c_idx'),
        ),
    ]
